name: Build and Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: |
          yarn install
      - name: Test
        env:
          CI: true
        run: |
          yarn lint && yarn test
      - name: Build
        run: |
          yarn dist
      - name: Release
        # if: github.ref == 'refs/heads/master'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: |
          yarn semantic-release
